micronaut:
  application:
    name: gateway
  http:
    services:
      userecho:
        urls:
          - "http://localhost:8081"
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'