micronaut:
  application:
    name: gateway
  http:
    services:
      userecho:
        urls:
          - "http://localhost:8081"
  security:
    authentication: bearer
    token:
      propagation:
        enabled: true
        service-id-regex: "userecho"
      oauth2:
        clients:
          google:
            client-id: '291650885725-gkeghigf2jmjskdjbm3enroq6crnhjtu.apps.googleusercontent.com'
            client-secret: '_k6jxqK8FkmX6yucbRFznxcs'
            openid:
              issuer: 'https://accounts.google.com'